### ISSUE TITLE
This is an app … Probably should be called `next-service-worker`

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/n-service-worker#3]
Strictly speaking this is an ‘app’ not a component as it is delivered over HTTP rather than pulled into another project as a code dependency via npm/bower/similar…  Probably ought to be renamed :-/

**Comment by wheresrhys** [comment]
Definitely needs renaming, Currently won't deploy

**Comment by wheresrhys** [comment]
nah :smile:
